out: std.fs.File.Writer,
symbol_prefix: []const u8,
/// Only reset when a new function is defined.
function_arena: std.heap.ArenaAllocator,
function_name: ?[]const u8 = null,
label_counter: u16 = 0,

const AsmWriter = @This();

fn panicWriterError(as: *AsmWriter) noreturn {
    @branchHint(.cold);
    std.debug.panic("{t}", .{as.out.err.?});
}

pub fn write(as: *AsmWriter, str: []const u8) void {
    as.out.interface.writeAll(str) catch as.panicWriterError();
}

pub fn writeVec(as: *AsmWriter, str: []const []const u8) void {
    as.out.interface.writeVec(str) catch as.panicWriterError();
}

pub fn print(as: *AsmWriter, comptime fmt: []const u8, args: anytype) void {
    as.out.interface.print(fmt, args) catch as.panicWriterError();
}

pub fn init(
    writer: std.fs.File.Writer,
    symbol_prefix: []const u8,
    arena: std.heap.ArenaAllocator,
) AsmWriter {
    var as = AsmWriter{
        .out = writer,
        .symbol_prefix = symbol_prefix,
        .function_arena = arena,
    };
    as.write(
        \\# WASM opcodes implemented in x86-64 assembly, used in the wasmstint interpreter
        \\#
        \\# This file is automatically generated.
        \\
        \\.intel_syntax noprefix
        \\.text
        \\
    );
    return as;
}

pub const Gpr = packed struct(u6) {
    tag: Tag,
    size: Size,

    pub const Size = enum(u2) {
        qword,
        dword,
        word,
        byte,

        pub fn toBits(size: Size) u5 {
            return switch (size) {
                .qword => 64,
                .dword => 32,
                .word => 16,
                .byte => 8,
            };
        }
    };

    pub const Tag = enum(u4) {
        a,
        b,
        c,
        d,

        src,
        dst,
        stack,
        base,

        @"8",
        @"9",
        @"10",
        @"11",

        @"12",
        @"13",
        @"14",
        @"15",
    };

    pub fn qword(tag: Tag) Gpr {
        return .{ .tag = tag, .size = .qword };
    }

    /// System V scratch register.
    pub const rax = Gpr.qword(.a);
    /// System V callee-saved register.
    pub const rbx = Gpr.qword(.b);
    /// System V scratch register.
    pub const rcx = Gpr.qword(.c);
    /// System V scratch register.
    pub const rdx = Gpr.qword(.d);

    /// System V scratch register.
    pub const rsi = Gpr.qword(.src);
    /// System V scratch register.
    pub const rdi = Gpr.qword(.dst);
    /// The stack-pointer, which for the purposes of writing the interpreter, is almost *never*
    /// modified.
    pub const rsp = Gpr.qword(.stack);
    /// The base/frame pointer, which for the purposes of writing the interpreter, is almost *never*
    /// modified.
    ///
    /// System V callee-saved register.
    ///
    /// Although using `rbp` could result in some code size savings, it allows Zig's panic handler
    /// to unwind the call stack, even when debug info is not emitted.
    pub const rbp = Gpr.qword(.base);

    /// System V scratch register.
    pub const r8 = Gpr.qword(.@"8");
    /// System V scratch register.
    pub const r9 = Gpr.qword(.@"9");
    /// System V scratch register.
    pub const r10 = Gpr.qword(.@"10");
    /// System V scratch register.
    pub const r11 = Gpr.qword(.@"11");

    /// System V callee-saved register.
    pub const r12 = Gpr.qword(.@"12");
    /// System V callee-saved register.
    pub const r13 = Gpr.qword(.@"13");
    /// System V callee-saved register.
    pub const r14 = Gpr.qword(.@"14");
    /// System V callee-saved register.
    pub const r15 = Gpr.qword(.@"15");

    pub const system_v_parameters: [6]Gpr = .{ .rdi, .rsi, .rdx, .rcx, .r8, .r9 };
    /// Excludes `rbp`.
    pub const system_v_callee_saved: [5]Gpr = .{ .r15, .r14, .r13, .r12, .rbx };

    pub fn withSize(reg: Gpr, size: Size) Gpr {
        var new_reg = reg;
        new_reg.size = size;
        return new_reg;
    }

    pub const eax = Gpr.rax.withSize(.dword);
    pub const ebx = Gpr.rbx.withSize(.dword);
    pub const ecx = Gpr.rcx.withSize(.dword);
    pub const edx = Gpr.rdx.withSize(.dword);
    pub const esi = Gpr.rsi.withSize(.dword);
    pub const edi = Gpr.rdi.withSize(.dword);
    //esp
    //rbp
    pub const r8d = Gpr.r8.withSize(.dword);
    pub const r9d = Gpr.r9.withSize(.dword);
    pub const r10d = Gpr.r10.withSize(.dword);
    pub const r11d = Gpr.r11.withSize(.dword);
    pub const r12d = Gpr.r12.withSize(.dword);
    pub const r13d = Gpr.r13.withSize(.dword);
    pub const r14d = Gpr.r14.withSize(.dword);
    pub const r15d = Gpr.r15.withSize(.dword);

    pub const ax = Gpr.rax.withSize(.word);
    pub const bx = Gpr.rbx.withSize(.word);
    pub const cx = Gpr.rcx.withSize(.word);
    pub const dx = Gpr.rdx.withSize(.word);
    pub const si = Gpr.rsi.withSize(.word);
    pub const di = Gpr.rdi.withSize(.word);
    //sp
    //bp
    pub const r8w = Gpr.r8.withSize(.word);
    pub const r9w = Gpr.r9.withSize(.word);
    pub const r10w = Gpr.r10.withSize(.word);
    pub const r11w = Gpr.r11.withSize(.word);
    pub const r12w = Gpr.r12.withSize(.word);
    pub const r13w = Gpr.r13.withSize(.word);
    pub const r14w = Gpr.r14.withSize(.word);
    pub const r15w = Gpr.r15.withSize(.word);

    pub const al = Gpr.rax.withSize(.byte);
    pub const bl = Gpr.rbx.withSize(.byte);
    pub const cl = Gpr.rcx.withSize(.byte);
    pub const dl = Gpr.rdx.withSize(.byte);
    pub const sil = Gpr.rsi.withSize(.byte);
    pub const dil = Gpr.rdi.withSize(.byte);
    //spl
    //bpl
    pub const r8b = Gpr.r8.withSize(.byte);
    pub const r9b = Gpr.r9.withSize(.byte);
    pub const r10b = Gpr.r10.withSize(.byte);
    pub const r11b = Gpr.r11.withSize(.byte);
    pub const r12b = Gpr.r12.withSize(.byte);
    pub const r13b = Gpr.r13.withSize(.byte);
    pub const r14b = Gpr.r14.withSize(.byte);
    pub const r15b = Gpr.r15.withSize(.byte);

    pub const vip = Gpr.rax;
    pub const stp = Gpr.rbx;
    pub const fuel = Gpr.rcx; // small savings if moved to other register, cl used for shift
    pub const module = Gpr.rdx; // TODO: infrequently used, small code size savings if moved to r8-15
    pub const vsp = Gpr.rsi;
    pub const locals = Gpr.rdi; // TODO: infrequently used, small code size savings if moved to r8-15
    pub const mems = Gpr.r8;
    pub const interp = Gpr.r9;
    pub const eip = Gpr.r10;
    /// Set only in handler for opcode prefix, currently only used to help debug invalid opcodes.
    pub const prefix_opcode_base_ip = Gpr.r11;
    pub const disp = Gpr.r12;

    pub const interpreter_state =
        [10]Gpr{ .vip, .stp, .fuel, .module, .vsp, .locals, .mems, .interp, .eip, .disp };

    pub fn name(reg: Gpr) []const u8 {
        return switch (reg.tag) {
            inline .a, .b, .c, .d => |tag| switch (reg.size) {
                .qword => &[3]u8{ 'r', @tagName(tag)[0], 'x' },
                .dword => &[3]u8{ 'e', @tagName(tag)[0], 'x' },
                .word => &[2]u8{ @tagName(tag)[0], 'x' },
                .byte => &[2]u8{ @tagName(tag)[0], 'l' },
            },
            inline .src, .dst, .stack, .base => |tag| name: {
                const middle = switch (tag) {
                    .src => "si",
                    .dst => "di",
                    .stack => "sp",
                    .base => "bp",
                    else => comptime unreachable,
                };

                break :name switch (reg.size) {
                    .qword => "r" ++ middle,
                    .dword => "e" ++ middle,
                    .word => middle,
                    .byte => middle ++ "l",
                };
            },
            inline else => |tag| name: {
                const prefix = comptime "r" ++ @tagName(tag);
                break :name switch (reg.size) {
                    .qword => prefix,
                    .dword => prefix ++ "d",
                    .word => prefix ++ "w",
                    .byte => prefix ++ "b",
                };
            },
        };
    }

    pub fn format(reg: Gpr, writer: *Writer) Writer.Error!void {
        try writer.writeAll(reg.name());
    }
};

/// All 15 are System V scratch registers.
const Xmm = enum(u3) {
    xmm0,
    xmm1,
    xmm2,
    xmm3,
    xmm4,
    xmm5,
    xmm6,
    xmm7,
    // can add 7 more if needed
};

fn nextNumberedLabel(as: *AsmWriter) u16 {
    const num = as.label_counter;
    as.label_counter += 1;
    return num;
}

pub const Label = struct {
    name_ptr: [*]const u8,
    name_len: u16,
    was_placed: bool = false,

    fn name(l: Label) []const u8 {
        return l.name_ptr[0..l.name_len];
    }

    pub fn place(l: *Label, as: *AsmWriter) void {
        std.debug.assert(!l.was_placed);
        l.was_placed = true;
        as.write(l.name());
        as.write(":\n");
    }

    pub fn format(l: Label, writer: *Writer) Writer.Error!void {
        try writer.writeAll(l.name());
    }
};

pub fn label(as: *AsmWriter, name: []const []const u8) Label {
    const function_name = as.function_name.?;
    const prefix = ".L";
    const num = as.nextNumberedLabel();
    const buf = as.function_arena.allocator().alloc(u8, size: {
        var size = prefix.len + as.symbol_prefix.len + function_name.len + 1 +
            (if (num == 0) 1 else std.math.log10_int(num) + 1);

        for (name) |s| {
            size += s.len;
        }

        break :size size;
    }) catch @panic("oom");

    var writer = Writer.fixed(buf);
    writer.writeAll(prefix) catch unreachable;
    writer.writeAll(as.symbol_prefix) catch unreachable;
    writer.writeAll(function_name) catch unreachable;
    writer.writeByte('_') catch unreachable;
    for (name) |s| {
        writer.writeAll(s) catch unreachable;
    }
    writer.printInt(num, 10, .lower, .{}) catch unreachable;

    const name_concat = writer.buffered();
    return .{
        .name_ptr = name_concat.ptr,
        .name_len = @intCast(name_concat.len),
    };
}

const Function = struct {
    name: [*]const u8,

    pub fn end(func: *Function, as: *AsmWriter) void {
        const func_name = as.function_name.?;
        std.debug.assert(@intFromPtr(func.name) == @intFromPtr(func_name.ptr));

        var end_label = as.label(&.{"end"});
        end_label.place(as);
        as.print(
            \\.size {[symbol_prefix]s}{[name]s}, {[label]s} - {[symbol_prefix]s}{[name]s} 
            \\# .cfi_endproc
            \\
        , .{ .symbol_prefix = as.symbol_prefix, .name = func_name, .label = end_label.name() });
        as.function_name = null;
        func.* = undefined;
    }
};

pub fn startFunction(
    as: *AsmWriter,
    /// Must match the pattern `[a-zA-Z_0-9\.]`.
    name: []const u8,
    alignment: std.mem.Alignment,
) Function {
    _ = as.function_arena.reset(.retain_capacity);
    as.function_name = name;
    as.label_counter = 0;
    as.print(
        \\
        \\.globl {[symbol_prefix]s}{[name]s}
        \\.p2align {[alignment]d}
        \\.type {[symbol_prefix]s}{[name]s}, @function
        \\{[symbol_prefix]s}{[name]s}:
        \\# .cfi_startproc
        \\
    , .{
        .symbol_prefix = as.symbol_prefix,
        .name = name,
        .alignment = @intFromEnum(alignment),
    });

    return Function{ .name = name.ptr };
}

pub fn finish(as: *AsmWriter) void {
    std.debug.assert(as.function_name == null);
    as.out.interface.flush() catch unreachable;
    as.* = undefined;
}

pub fn printInstrs(as: *AsmWriter, comptime fmt: []const []const u8, args: anytype) void {
    const actual_fmt = comptime fmt: {
        var f: []const u8 = "";
        for (fmt) |s| {
            f = f ++ "\t" ++ s ++ "\n";
        }
        break :fmt f;
    };

    as.print(actual_fmt, args);
}

pub fn writeInstrs(as: *AsmWriter, lines: []const []const u8) void {
    for (lines) |s| {
        if (s.len > 0) {
            as.write("\t");
            as.write(s);
        }
        as.write("\n");
    }
}

pub const OpcodeHandler = struct {
    function: Function,
    out_of_fuel: Label,

    pub fn end(handler: *OpcodeHandler, as: *AsmWriter) void {
        handler.out_of_fuel.place(as);
        as.printInstrs(&.{
            "jmp {[symbol_prefix]s}outOfFuelHandler",
            "ud2",
        }, .{
            .symbol_prefix = as.symbol_prefix,
        });

        handler.function.end(as);
        handler.* = undefined;
    }

    pub fn jmpToNextHandler(handler: *const OpcodeHandler, as: *AsmWriter) void {
        std.debug.assert(@intFromPtr(handler.function.name) == @intFromPtr(as.function_name.?.ptr));

        // TODO: Store fuel directly instead of via pointer, include fuel in return value
        // ^ System V supports two return registers

        as.printInstrs(&.{
            "movzx r11, byte ptr [{[vip]f}] # read next opcode byte",
            "sub qword ptr [{[fuel]f}], 1 # fuel check",
            "jb {[out_of_fuel]s}",

            "# jump to the next handler",
            "inc {[vip]f}",
            "mov r11, qword ptr [{[disp]f} + r11*8] # load next handler",
            "jmp r11",
            "ud2",
        }, .{
            .vip = Gpr.vip,
            .fuel = Gpr.fuel,
            .out_of_fuel = handler.out_of_fuel.name(),
            .disp = Gpr.disp,
        });
    }
};

pub const SystemVParam = struct {
    index: u8,
    size: Gpr.Size = .qword,

    pub fn format(param: SystemVParam, writer: *Writer) Writer.Error!void {
        if (param.index < Gpr.system_v_parameters.len) {
            try writer.writeAll(Gpr.system_v_parameters[param.index].withSize(param.size).name());
        } else {
            try writer.print("{[size]t} ptr [rbp + {[disp]d}]", .{
                .size = param.size,
                .disp = (param.index - Gpr.system_v_parameters.len + 2) * 8,
            });
        }
    }
};

pub const PreservedRegisters = struct {
    registers: []const Gpr,
    comments: []const []const u8,

    pub fn preserve(info: *const PreservedRegisters, as: *AsmWriter) void {
        for (info.registers, info.comments) |reg, comment| {
            as.printInstrs(&.{"push {[reg]f} # {[comment]s}"}, .{ .reg = reg, .comment = comment });
        }
    }

    pub fn restore(info: *const PreservedRegisters, as: *AsmWriter) void {
        for (0..info.comments.len) |forward_idx| {
            const i = info.comments.len - forward_idx - 1;
            as.printInstrs(
                &.{"pop {[reg]f} # {[comment]s}"},
                .{ .reg = info.registers[i], .comment = info.comments[i] },
            );
        }
    }
};

pub fn defineOpcodeHandler(
    as: *AsmWriter,
    zig: *ZigWriter,
    name: []const u8,
    alignment: std.mem.Alignment,
) OpcodeHandler {
    const func = as.startFunction(name, alignment);
    zig.defineOpcodeHandler(name);
    return .{ .function = func, .out_of_fuel = as.label(&.{"out_of_fuel"}) };
}

pub fn restoreSystemVSavedRegisters(as: *AsmWriter) void {
    as.write("\t# restore System V callee-saved registers\n");
    for (Gpr.system_v_parameters.len.., Gpr.system_v_callee_saved) |i, saved| {
        as.printInstrs(
            &.{"mov {[saved]s}, {[slot]f}"},
            .{ .saved = saved.name(), .slot = SystemVParam{ .index = @intCast(i) } },
        );
    }
}

const std = @import("std");
const Writer = std.Io.Writer;
const ZigWriter = @import("ZigWriter");
