//! Not really an x86-64 assembler, just helps write x86-64 assembly with additional checks.
//!
//! Does not check errors that would be caught by the actual assembler, e.g. using a wrong operand.

out: std.fs.File.Writer,
symbol_prefix: []const u8,
arena: std.heap.ArenaAllocator,
function_name: ?[]const u8 = null,
label_counter: u32 = 0,
/// Which registers should't be modified.
no_clobber_gprs: std.EnumSet(Gpr.Tag) = .initEmpty(),
uninitialized_gprs: std.EnumSet(Gpr.Tag) = .initEmpty(),

const Assembler = @This();

pub fn init(
    writer: std.fs.File.Writer,
    symbol_prefix: []const u8,
    arena: std.heap.ArenaAllocator,
) Assembler {
    var out = writer;
    out.interface.writeAll(
        \\# WASM opcodes implemented in x86-64 assembly, used in the wasmstint interpreter
        \\#
        \\# This file is automatically generated.
        \\
        \\.intel_syntax noprefix
        \\.text
        \\
    ) catch std.debug.panic("{t}", .{out.err.?});
    return .{ .out = out, .symbol_prefix = symbol_prefix, .arena = arena };
}

pub const Gpr = packed struct(u7) {
    tag: Tag,
    size: Size,

    pub const Size = enum(u2) {
        qword,
        dword,
        word,
        byte,
    };

    pub const Tag = enum(u5) {
        a,
        b,
        c,
        d,

        src,
        dst,
        stack,
        base,

        @"8",
        @"9",
        @"10",
        @"11",

        @"12",
        @"13",
        @"14",
        @"15",

        /// Excludes `rbp`.
        pub const system_v_callee_saved: [5]Gpr.Tag = .{ .@"15", .@"14", .@"13", .@"12", .b };

        pub const system_v_parameters: [6]Gpr.Tag = .{ .dst, .src, .d, .c, .@"8", .@"9" };

        pub const no_rsp_or_rbp: [14]Gpr.Tag = .{
            .a,
            .b,
            .c,
            .d,
            .src,
            .dst,
            .@"8",
            .@"9",
            .@"10",
            .@"11",
            .@"12",
            .@"13",
            .@"14",
            .@"15",
        };

        fn setFormatter(set: std.EnumSet(Gpr.Tag)) FormatSet {
            return .{ .set = set };
        }

        const FormatSet = struct {
            set: std.EnumSet(Gpr.Tag),

            pub fn format(f: @This(), writer: *std.Io.Writer) std.Io.Writer.Error!void {
                var start = true;
                var iter = f.set.iterator();
                while (iter.next()) |next| {
                    if (!start) {
                        try writer.writeAll(", ");
                    }
                    start = false;
                    try writer.writeAll(Gpr.qword(next).name());
                }
            }
        };
    };

    pub fn qword(tag: Tag) Gpr {
        return .{ .tag = tag, .size = .qword };
    }

    /// System V scratch register.
    pub const rax = Gpr.qword(.a);
    /// System V callee-saved register.
    pub const rbx = Gpr.qword(.b);
    /// System V scratch register.
    pub const rcx = Gpr.qword(.c);
    /// System V scratch register.
    pub const rdx = Gpr.qword(.d);

    /// System V scratch register.
    pub const rsi = Gpr.qword(.src);
    /// System V scratch register.
    pub const rdi = Gpr.qword(.dst);
    /// The stack-pointer, which for the purposes of writing the interpreter, is almost *never*
    /// modified.
    pub const rsp = Gpr.qword(.stack);
    /// The base/frame pointer, which for the purposes of writing the interpreter, is almost *never*
    /// modified.
    ///
    /// System V callee-saved register.
    ///
    /// Although using `rbp` could result in some code size savings, it allows Zig's panic handler
    /// to unwind the call stack, even when debug info is not emitted.
    pub const rbp = Gpr.qword(.base);

    /// System V scratch register.
    pub const r8 = Gpr.qword(.@"8");
    /// System V scratch register.
    pub const r9 = Gpr.qword(.@"9");
    /// System V scratch register.
    pub const r10 = Gpr.qword(.@"10");
    /// System V scratch register.
    pub const r11 = Gpr.qword(.@"11");

    /// System V callee-saved register.
    pub const r12 = Gpr.qword(.@"12");
    /// System V callee-saved register.
    pub const r13 = Gpr.qword(.@"13");
    /// System V callee-saved register.
    pub const r14 = Gpr.qword(.@"14");
    /// System V callee-saved register.
    pub const r15 = Gpr.qword(.@"15");

    pub const system_v_parameters: [6]Gpr = regs: {
        var regs: [6]Gpr = undefined;
        for (&regs, Tag.system_v_parameters) |*r, tag| {
            r.* = Gpr.qword(tag);
        }
        break :regs regs;
    };

    pub fn withSize(reg: Gpr, size: Size) Gpr {
        var new_reg = reg;
        new_reg.size = size;
        return new_reg;
    }

    pub const eax = Gpr.rax.withSize(.dword);
    pub const ebx = Gpr.rbx.withSize(.dword);
    pub const ecx = Gpr.rcx.withSize(.dword);
    pub const edx = Gpr.rdx.withSize(.dword);
    pub const esi = Gpr.rsi.withSize(.dword);
    pub const edi = Gpr.rdi.withSize(.dword);
    //esp
    //rbp
    pub const r8d = Gpr.r8.withSize(.dword);
    pub const r9d = Gpr.r9.withSize(.dword);
    pub const r10d = Gpr.r10.withSize(.dword);
    pub const r11d = Gpr.r11.withSize(.dword);
    pub const r12d = Gpr.r12.withSize(.dword);
    pub const r13d = Gpr.r13.withSize(.dword);
    pub const r14d = Gpr.r14.withSize(.dword);
    pub const r15d = Gpr.r15.withSize(.dword);

    pub const ax = Gpr.rax.withSize(.word);
    pub const bx = Gpr.rbx.withSize(.word);
    pub const cx = Gpr.rcx.withSize(.word);
    pub const dx = Gpr.rdx.withSize(.word);
    pub const si = Gpr.rsi.withSize(.word);
    pub const di = Gpr.rdi.withSize(.word);
    //sp
    //bp
    pub const r8w = Gpr.r8.withSize(.word);
    pub const r9w = Gpr.r9.withSize(.word);
    pub const r10w = Gpr.r10.withSize(.word);
    pub const r11w = Gpr.r11.withSize(.word);
    pub const r12w = Gpr.r12.withSize(.word);
    pub const r13w = Gpr.r13.withSize(.word);
    pub const r14w = Gpr.r14.withSize(.word);
    pub const r15w = Gpr.r15.withSize(.word);

    pub const al = Gpr.rax.withSize(.byte);
    pub const bl = Gpr.rbx.withSize(.byte);
    pub const cl = Gpr.rcx.withSize(.byte);
    pub const dl = Gpr.rdx.withSize(.byte);
    pub const sil = Gpr.rsi.withSize(.byte);
    pub const dil = Gpr.rdi.withSize(.byte);
    //spl
    //bpl
    pub const r8b = Gpr.r8.withSize(.byte);
    pub const r9b = Gpr.r9.withSize(.byte);
    pub const r10b = Gpr.r10.withSize(.byte);
    pub const r11b = Gpr.r11.withSize(.byte);
    pub const r12b = Gpr.r12.withSize(.byte);
    pub const r13b = Gpr.r13.withSize(.byte);
    pub const r14b = Gpr.r14.withSize(.byte);
    pub const r15b = Gpr.r15.withSize(.byte);

    pub const vip = Gpr.rax;
    pub const stp = Gpr.rbx;
    pub const fuel = Gpr.rcx; // small savings if moved to other register, cl used for shift
    pub const module = Gpr.rdx; // TODO: infrequently used, small code size savings if moved to r8-15
    pub const vsp = Gpr.rsi;
    pub const locals = Gpr.rdi; // TODO: infrequently used, small code size savings if moved to r8-15
    pub const mems = Gpr.r8;
    pub const interp = Gpr.r9;
    pub const eip = Gpr.r10;
    // r11
    pub const disp = Gpr.r12;

    pub const interpreter_state =
        [10]Gpr{ .vip, .stp, .fuel, .module, .vsp, .locals, .mems, .interp, .eip, .disp };

    pub fn sliceToTagSet(registers: []const Gpr) std.EnumSet(Tag) {
        var tags = std.EnumSet(Gpr.Tag).initEmpty();
        for (registers) |reg| {
            tags.insert(reg.tag);
        }
        return tags;
    }

    pub fn name(reg: Gpr) []const u8 {
        return switch (reg.tag) {
            inline .a, .b, .c, .d => |tag| switch (reg.size) {
                .qword => &[3]u8{ 'r', @tagName(tag)[0], 'x' },
                .dword => &[3]u8{ 'e', @tagName(tag)[0], 'x' },
                .word => &[2]u8{ @tagName(tag)[0], 'x' },
                .byte => &[2]u8{ @tagName(tag)[0], 'l' },
            },
            inline .src, .dst, .stack, .base => |tag| name: {
                const middle = switch (tag) {
                    .src => "si",
                    .dst => "di",
                    .stack => "sp",
                    .base => "bp",
                    else => comptime unreachable,
                };

                break :name switch (reg.size) {
                    .qword => "r" ++ middle,
                    .dword => "e" ++ middle,
                    .word => middle,
                    .byte => middle ++ "l",
                };
            },
            inline else => |tag| name: {
                const prefix = comptime "r" ++ @tagName(tag);
                break :name switch (reg.size) {
                    .qword => prefix,
                    .dword => prefix ++ "d",
                    .word => prefix ++ "w",
                    .byte => prefix ++ "b",
                };
            },
        };
    }
};

pub inline fn markInitialized(as: *Assembler, registers: std.EnumSet(Gpr.Tag)) void {
    as.uninitialized_gprs.setIntersection(registers.complement());
}

pub fn preventClobbering(as: *Assembler, registers: std.EnumSet(Gpr.Tag)) void {
    const check_clobber_uninit = as.uninitialized_gprs.intersectWith(registers);
    if (check_clobber_uninit.count() != 0) {
        @branchHint(.cold);
        std.debug.panic(
            "can't prevent clobber of uninitialized: {f}",
            .{Gpr.Tag.setFormatter(check_clobber_uninit)},
        );
    }
    as.no_clobber_gprs.setUnion(registers);
}

pub fn allowClobbering(as: *Assembler, register: std.EnumSet(Gpr.Tag)) void {
    as.no_clobber_gprs = as.no_clobber_gprs.differenceWith(register);
}

/// Asserts that `register` is currently prevented from being clobbered
pub fn allowClobberingStrict(as: *Assembler, registers: std.EnumSet(Gpr.Tag)) void {
    const check_no_clobber = as.uninitialized_gprs.intersectWith(registers);
    if (check_no_clobber.count() != 0) {
        @branchHint(.cold);
        std.debug.panic(
            "already marked no clobber: {f}",
            .{Gpr.Tag.setFormatter(check_no_clobber)},
        );
    }

    as.allowClobbering(registers);
}

pub fn nextUninitializedRegister(as: *Assembler) Gpr.Tag {
    var iter = as.uninitialized_gprs.iterator();
    const chosen = iter.next() orelse @panic("out of registers!");
    std.debug.assert(!as.no_clobber_gprs.contains(chosen));
    return chosen;
}

inline fn printGpr(as: *Assembler, gpr: Gpr) void {
    as.print(gpr.name());
}

// Could be like Gpr if support for Ymm registers is needed
/// All 15 are System V scratch registers.
const Xmm = enum(u3) {
    xmm0,
    xmm1,
    xmm2,
    xmm3,
    xmm4,
    xmm5,
    xmm6,
    xmm7,
    // can add 7 more if needed
};

fn panicWriterError(as: *Assembler) noreturn {
    @branchHint(.cold);
    std.debug.panic("{t}", .{as.out.err.?});
}

/// Don't forget the newline at the end!
fn print(as: *Assembler, str: []const u8) void {
    as.out.interface.writeAll(str) catch as.panicWriterError();
}

/// Don't forget the newline at the end!
fn printMany(as: *Assembler, strings: []const []const u8) void {
    for (strings) |s| {
        as.print(s);
    }
}

const PrintIntBase = enum(u5) { dec = 10, hex = 16 };

const PrintIntOptions = struct {
    width: ?usize = null,
    fill: u8 = '0',
};

fn printIntWithOptions(
    as: *Assembler,
    value: anytype,
    base: PrintIntBase,
    options: PrintIntOptions,
) void {
    switch (base) {
        .dec => {},
        .hex => as.print("0x"),
    }

    as.out.interface.printInt(value, @intFromEnum(base), .upper, .{
        .width = options.width,
        .fill = options.fill,
    }) catch as.panicWriterError();
}

fn printInt(as: *Assembler, value: anytype) void {
    as.printIntWithOptions(value, .dec, .{});
}

pub fn writeComment(
    as: *Assembler,
    /// Shouldn't contain embedded newlines.
    comment: []const u8,
) void {
    as.printMany(&.{ "# ", comment, "\n" });
}

pub fn writeCommentMultiLine(
    as: *Assembler,
    /// Shouldn't contain embedded newlines.
    comments: []const []const u8,
) void {
    for (comments) |s| {
        as.writeComment(s);
    }
}

fn nextNumberedLabel(as: *Assembler) u32 {
    const num = as.label_counter;
    as.label_counter += 1;
    return num;
}

pub const Label = struct {
    name_ptr: [*]const u8,
    name_len: u16,
    placed: bool = false,
    number: u32,
    function_name: [*]const u8,

    fn name(l: Label) []const u8 {
        return l.name_ptr[0..l.name_len];
    }

    pub fn place(l: *Label, as: *Assembler) void {
        std.debug.assert(!l.placed);
        l.placed = true;
        as.printLabelName(l);
        as.print(":\n");
    }
};

fn printLabelName(as: *Assembler, l: *const Label) void {
    const func_name = as.function_name.?;
    std.debug.assert(@intFromPtr(func_name.ptr) == @intFromPtr(l.function_name));
    as.printMany(&.{ ".L", as.symbol_prefix, func_name, "_", l.name() });
    as.printInt(l.number);
}

pub fn label(as: *Assembler, name: []const u8) Label {
    return .{
        .function_name = as.function_name.?.ptr,
        .name_ptr = name.ptr,
        .name_len = @intCast(name.len),
        .number = as.nextNumberedLabel(),
    };
}

const Function = struct {
    name: [*]const u8,

    pub fn end(func: Function, as: *Assembler) void {
        const func_name = as.function_name.?;
        std.debug.assert(@intFromPtr(func.name) == @intFromPtr(func_name.ptr));

        var end_label = as.label("end");
        end_label.place(as);
        as.printMany(&.{ ".size ", as.symbol_prefix, func_name, ", " });
        as.printLabelName(&end_label);
        as.printMany(&.{ " - ", as.symbol_prefix, func_name });
        as.print("\n# .cfi_endproc\n");
        as.function_name = null;
    }
};

pub fn p2align(as: *Assembler, alignment: std.mem.Alignment) void {
    as.print(".p2align ");
    as.printInt(@intFromEnum(alignment));
    as.print("\n");
}

pub fn startFunction(
    as: *Assembler,
    /// Must match the pattern `[a-zA-Z_0-9\.]`.
    name: []const u8,
    alignment: std.mem.Alignment,
) Function {
    as.function_name = name;
    as.no_clobber_gprs = .initEmpty();
    as.uninitialized_gprs = comptime .initMany(&Gpr.Tag.no_rsp_or_rbp);
    as.printMany(&.{ "\n.globl ", as.symbol_prefix, name });
    as.print("\n");
    as.p2align(alignment);
    as.printMany(&.{ ".type ", as.symbol_prefix, name, ", @function\n" });
    as.printMany(&.{ as.symbol_prefix, name, ":\n" });
    as.print("# .cfi_startproc\n");
    return Function{ .name = name.ptr };
}

pub fn checkRegisterInitialized(as: *Assembler, reg: Gpr.Tag) void {
    if (as.uninitialized_gprs.contains(reg)) {
        @branchHint(.cold);
        std.debug.panic("register {t} is uninitialized", .{reg});
    }
}

pub fn checkRegisterClobber(as: *Assembler, reg: Gpr.Tag) void {
    if (as.no_clobber_gprs.contains(reg)) {
        @branchHint(.cold);
        std.debug.panic(
            "cannot clobber register {s}/{s}/{s}",
            .{ Gpr.qword(reg).name(), Gpr.name(.{ .tag = reg, .size = .dword }), Gpr.name(
                .{ .tag = reg, .size = .word },
            ) },
        );
    }
}

pub const Symbol = struct {
    name_ptr: [*]const u8,
    name_len: u32,
    prefixed: bool,

    pub fn initPrefixed(name: []const u8) Symbol {
        return .{ .name_ptr = name.ptr, .name_len = @intCast(name.len), .prefixed = true };
    }

    pub fn nameUnprefixed(symbol: Symbol) []const u8 {
        return symbol.name_ptr[0..symbol.name_len];
    }

    pub const byte_dispatch_table = Symbol.initPrefixed("byte_dispatch_table");
    pub const out_of_fuel_handler = Symbol.initPrefixed("outOfFuelHandler");
    pub const interrupt_out_of_fuel = Symbol.initPrefixed("interruptOutOfFuel");
};

fn printSymbol(as: *Assembler, sym: Symbol) void {
    if (sym.prefixed) {
        as.print(as.symbol_prefix);
    }
    as.print(sym.nameUnprefixed());
}

pub const Operand = union(enum) {
    gpr: Gpr,
    xmm: Xmm,
    u8: u8,
    u32: u32,
    mem: Mem,
    label: *const Label,
    symbol: Symbol,

    pub fn paramFromRbp(offset: usize, size: Gpr.Size) Operand {
        return .{
            .mem = .{
                .size = .fromGprSize(size),
                .base = .rbp,
                .disp = .{ .literal = @intCast((offset + 2) * 8) },
            },
        };
    }

    pub const Mem = struct {
        size: Size,
        base: ?Gpr = null,
        index: ?Gpr = null,
        scale: Scale = .@"1",
        disp: Displacement = .{ .literal = 0 },

        pub const Size = enum {
            xmmword,
            qword,
            dword,
            word,
            byte,

            pub fn fromGprSize(size: Gpr.Size) Size {
                return switch (size) {
                    inline else => |chosen| @field(Size, @tagName(chosen)),
                };
            }
        };

        pub const Scale = enum(u2) { @"1", @"2", @"4", @"8" };

        pub const Displacement = union(enum) {
            literal: i32,
            symbol: Symbol,

            fn isZero(disp: Displacement) bool {
                return disp == .literal and disp.literal == 0;
            }
        };
    };
};

pub fn instr(
    as: *Assembler,
    name: []const u8,
    operands: []const Operand,
    /// Must not contain any newlines.
    comment: []const u8,
) void {
    as.print("\t");
    as.print(name);
    for (operands, 0..) |op, i| {
        as.print(if (i == 0) " " else ", ");
        switch (op) {
            .gpr => |gpr| {
                if (i == 0) {
                    as.checkRegisterClobber(gpr.tag); // check destination
                    as.uninitialized_gprs.remove(gpr.tag);
                } else {
                    as.checkRegisterInitialized(gpr.tag);
                }
                as.printGpr(gpr);
            },
            .xmm => |xmm| as.print(@tagName(xmm)),
            .symbol => |sym| as.printSymbol(sym),
            .label => |l| as.printLabelName(l),
            inline .u8, .u32 => |value| as.printIntWithOptions(
                value,
                if (value < 0xA) .dec else .hex,
                .{},
            ),
            .mem => |mem| {
                as.print(@tagName(mem.size));
                as.print(" ptr [");
                if (mem.base) |base| {
                    as.printGpr(base);
                }

                if (mem.index) |index| {
                    if (mem.base != null) {
                        as.print(" + ");
                    } else {
                        std.debug.assert(mem.scale != .@"1" or !mem.disp.isZero()); // use base instead
                    }
                    as.printGpr(index);
                }

                if (mem.scale != .@"1") {
                    if (mem.base != null or mem.index != null) {
                        as.print("*");
                    }
                    as.print(@tagName(mem.scale));
                }

                if (!mem.disp.isZero()) {
                    if (mem.base != null or mem.index != null) {
                        as.print(" + ");
                    }
                    switch (mem.disp) {
                        .literal => |disp| as.printIntWithOptions(
                            disp,
                            if (@rem(disp, 16) == 0) .hex else .dec,
                            .{},
                        ),
                        .symbol => |symbol| as.printSymbol(symbol),
                    }
                }

                as.print("]");
            },
        }
    }

    if (comment.len != 0) {
        as.print(" # ");
        as.print(comment);
    }

    as.print("\n");
}

/// Common condition flags used in isntructions such as `jcc`, `cmovcc`, etc.
///
/// Note that `jcc` also has additional conditions not listed here (e.g. `jcxz`).
pub const Condition = enum {
    a,
    ae,
    b,
    be,
    c,
    e,
    g,
    ge,
    l,
    le,
    na,
    nae,
    nb,
    nbe,
    nc,
    ne,
    ng,
    nge,
    nl,
    nle,
    no,
    np,
    ns,
    nz,
    o,
    p,
    pe,
    po,
    s,
    z,

    fn name(cond: Condition, comptime prefix: []const u8, buffer: *[prefix.len + 3]u8) []const u8 {
        const cond_name = @tagName(cond);
        const final_len = prefix.len + cond_name.len;
        @memcpy(buffer[0..prefix.len], prefix);
        @memcpy(buffer[prefix.len..final_len], cond_name);
        return buffer[0..final_len];
    }
};

/// https://www.felixcloutier.com/x86/inc
pub fn inc(as: *Assembler, dst: Operand, comment: []const u8) void {
    as.instr("inc", &.{dst}, comment);
}

/// https://www.felixcloutier.com/x86/jcc
pub fn jcc(as: *Assembler, cond: Condition, target: Operand, comment: []const u8) void {
    var name_buf: [4]u8 = undefined;
    as.instr(cond.name("j", &name_buf), &.{target}, comment);
}

/// https://www.felixcloutier.com/x86/jmp
pub fn jmp(as: *Assembler, target: Operand, comment: []const u8) void {
    as.instr("jmp", &.{target}, comment);
}

/// https://www.felixcloutier.com/x86/lea
pub fn lea(as: *Assembler, dst: Gpr, src: Operand, comment: []const u8) void {
    as.instr("lea", &.{ .{ .gpr = dst }, src }, comment);
}

/// https://www.felixcloutier.com/x86/mov
pub fn mov(as: *Assembler, dst: Operand, src: Operand, comment: []const u8) void {
    as.instr("mov", &.{ dst, src }, comment);
}

/// https://www.felixcloutier.com/x86/movzx
pub fn movzx(as: *Assembler, dst: Gpr, src: Operand, comment: []const u8) void {
    as.instr("movzx", &.{ .{ .gpr = dst }, src }, comment);
}

/// https://www.felixcloutier.com/x86/pop
pub fn pop(as: *Assembler, op: Operand, comment: []const u8) void {
    as.instr("pop", &.{op}, comment);
}

/// https://www.felixcloutier.com/x86/push
pub fn push(as: *Assembler, op: Operand, comment: []const u8) void {
    as.instr("push", &.{op}, comment);
}

/// https://www.felixcloutier.com/x86/sub
pub fn sub(as: *Assembler, dst: Operand, src: Operand, comment: []const u8) void {
    as.instr("sub", &.{ dst, src }, comment);
}

/// https://www.felixcloutier.com/x86/ud
pub fn ud2(as: *Assembler) void {
    as.instr("ud2", &.{}, "");
}

pub fn finish(as: *Assembler) void {
    std.debug.assert(as.function_name == null);
    as.out.interface.flush() catch unreachable;
    as.* = undefined;
}

pub const OpcodeHandler = struct {
    function: Function,
    out_of_fuel: Label,

    pub fn end(handler: *OpcodeHandler, as: *Assembler) void {
        handler.out_of_fuel.place(as);
        as.jmp(.{ .symbol = .out_of_fuel_handler }, "");
        as.ud2();

        handler.function.end(as);
        handler.* = undefined;
    }

    pub fn jmpToNextHandler(
        handler: *const OpcodeHandler,
        as: *Assembler,
        temp: Gpr,
    ) void {
        // TODO: Store fuel directly instead of via pointer, include fuel in return value
        // System V supports two return registers
        std.debug.assert(temp.size == .qword);
        as.movzx(temp, .{ .mem = .{ .size = .byte, .base = .vip } }, "read next opcode byte");
        as.sub(.{ .mem = .{ .size = .qword, .base = .fuel } }, .{ .u8 = 1 }, "fuel check");
        as.jcc(.b, .{ .label = &handler.out_of_fuel }, "");
        as.writeComment("jump to the next handler");
        as.inc(.{ .gpr = .vip }, "vip");
        // \\    mov {[temp]t}, qword ptr [{[disp]t} + {[temp]t} * 8]
        as.mov(
            .{ .gpr = temp },
            .{ .mem = .{ .size = .qword, .base = .disp, .index = temp, .scale = .@"8" } },
            "load next handler",
        );
        as.jmp(.{ .gpr = temp }, "");
        as.ud2();
    }
};

pub fn defineOpcodeHandler(
    as: *Assembler,
    zig: *ZigWriter,
    name: []const u8,
    alignment: std.mem.Alignment,
) OpcodeHandler {
    const func = as.startFunction(name, alignment);
    zig.defineOpcodeHandler(name);
    const interpreter_state = comptime Gpr.sliceToTagSet(&Gpr.interpreter_state);
    as.markInitialized(interpreter_state);
    as.preventClobbering(
        as.no_clobber_gprs
            .unionWith(comptime interpreter_state.unionWith(.initMany(&.{ .stack, .base })))
            .differenceWith(.initOne(Gpr.vip.tag)),
    );
    return .{ .function = func, .out_of_fuel = as.label("out_of_fuel") };
}

pub fn restoreSystemVSavedRegisters(as: *Assembler) void {
    as.writeComment("restore System V callee-saved registers");
    for (0.., Gpr.Tag.system_v_callee_saved) |i, tag| {
        as.mov(.{ .gpr = Gpr.qword(tag) }, .paramFromRbp(i, .qword), "");
    }
}

const std = @import("std");
const ZigWriter = @import("ZigWriter");
