out: std.fs.File.Writer,
symbol_prefix: []const u8,

const ZigWriter = @This();

pub fn init(writer: std.fs.File.Writer, symbol_prefix: []const u8) ZigWriter {
    var out = writer;
    out.interface.writeAll(
        \\//! This file is automatically generated.
        \\
        \\/// Generates references to the individual opcode handlers in the generated assembly.
        \\/// TODO: Organize wasmstint into modules so this doesn't need to be a function
        \\/// TODO: Write comptime checks for layout of runtime structures
        \\pub fn handlers(comptime OpcodeHandler: type) type {
        \\    return struct {
    ) catch std.debug.panic("{t}", .{out.err.?});
    return .{ .out = out, .symbol_prefix = symbol_prefix };
}

fn print(writer: *ZigWriter, s: []const u8) void {
    writer.out.interface.writeAll(s) catch std.debug.panic("{t}", .{writer.out.err.?});
}

pub fn defineOpcodeHandlerAlias(writer: *ZigWriter, name: []const u8, as: []const u8) void {
    writer.print((" " ** 8) ++ "pub const @\"");
    writer.print(as);
    writer.print("\" = @extern(OpcodeHandler, .{ .name = \"");
    writer.print(writer.symbol_prefix);
    writer.print(name);
    writer.print("\" });\n");
}

pub inline fn defineOpcodeHandler(writer: *ZigWriter, name: []const u8) void {
    return writer.defineOpcodeHandlerAlias(name, name);
}

pub fn finish(writer: *ZigWriter) void {
    writer.out.interface.writeAll(
        \\    };
        \\}
        \\
    ) catch unreachable;
    writer.out.interface.flush() catch unreachable;
    writer.* = undefined;
}

const std = @import("std");
