//! Floating-point rounding operations following WebAssembly semantics.

pub fn operations(comptime F: type) type {
    return struct {
        const is_vector = switch (@typeInfo(F)) {
            .float => false,
            .vector => true,
            else => @compileError("expected float or vector type"),
        };

        const Scalar = if (is_vector) @typeInfo(F).vector.child else F;

        comptime {
            switch (Scalar) {
                f32, f64 => {},
                else => @compileError("unsupported float type " ++ @typeName(F)),
            }
        }

        const Vector = if (is_vector) F else @Vector(1, F);
        const vector_len = if (is_vector) @typeInfo(F).vector.len else 1;

        const bit_width = @typeInfo(Scalar).float.bits;
        const SignedInt = std.meta.Int(.signed, bit_width);
        const BitInt = std.meta.Int(.unsigned, bit_width);
        const ExponentInt = std.math.FloatRepr(Scalar).Exponent;

        const canonical_nan_bit_pattern: BitInt = 1 << (std.math.floatMantissaBits(F) - 1);
        const precise_int_limit_value = 1 << (std.math.floatMantissaBits(F) + 1);
        /// Above (or below if negative) this limit, only integers are representable.
        const precise_int_limit: F = precise_int_limit_value;

        inline fn splat(comptime T: type, value: T) @Vector(vector_len, T) {
            return @splat(value);
        }

        /// Since this module handles both rounding for both scalars and vectors, branch-less code
        /// is always used.
        inline fn select(
            comptime T: type,
            predicate: @Vector(vector_len, bool),
            true_case: @Vector(vector_len, T),
            false_case: @Vector(vector_len, T),
        ) @Vector(vector_len, T) {
            return @select(T, predicate, true_case, false_case);
        }

        inline fn input(z: F) Vector {
            return if (is_vector) z else splat(Scalar, z);
        }

        inline fn bitCastLane(comptime T: type, value: anytype) @Vector(vector_len, T) {
            comptime std.debug.assert(@typeInfo(@TypeOf(value)).vector.len == vector_len);
            return @bitCast(value);
        }

        inline fn setCanonicalNanBit(z: Vector) Vector {
            return @bitCast(bitCastLane(BitInt, z) | splat(BitInt, canonical_nan_bit_pattern));
        }

        /// Constructs the result value, ensuring NaN's are of the correct type.
        ///
        /// Intrinsics do not specify what NaN can be returned when a NaN input is provided. This
        /// ensures that the provided NaN matches the set that can be returned from any operation
        /// in WebAssembly.
        ///
        /// Note that the rounding instructions (e.g. `roundss`) generated by the compiler when
        /// targeting X86-64 with SSE4.1 seem to follow WASM semantics already, but that behavior
        /// is not relied on here.
        inline fn result(z: Vector) F {
            const f = select(
                F,
                z != z, // Is this a NaN?
                setCanonicalNanBit(z),
                z,
            );

            return if (is_vector) f else f[0];
        }

        /// https://webassembly.github.io/spec/core/exec/numerics.html#op-fceil
        pub fn ceil(z: F) F {
            return result(@ceil(input(z)));
        }

        /// https://webassembly.github.io/spec/core/exec/numerics.html#op-ffloor
        pub fn floor(z: F) F {
            return result(@floor(input(z)));
        }

        /// https://webassembly.github.io/spec/core/exec/numerics.html#op-ftrunc
        pub fn trunc(z: F) F {
            const f = input(z);
            return result(
                select(
                    F,
                    f <= splat(Scalar, -0.0),
                    @ceil(f),
                    @floor(f),
                ),
            );
        }

        /// https://webassembly.github.io/spec/core/exec/numerics.html#op-fnearest
        pub fn nearest(z: F) F {
            // WASM requires rounds-to-nearest-ties-even

            // '@round' compiles to 'llvm.round.*', but what is needed is 'llvm.roundeven.*'
            // See also:
            // - https://github.com/ziglang/zig/issues/767
            // - https://github.com/ziglang/zig/issues/2535

            // Caution, might get error: "Invalid user of intrinsic instruction!"
            // extern fn @"llvm.roundeven.f32"(z: f32) callconv(.c) f32;
            // extern fn @"llvm.roundeven.f64"(z: f64) callconv(.c) f64;

            // Also seems to be available in C23, but that's too new:
            // extern "c" fn roundevenf(arg: f32) f32;
            // extern "c" fn roundeven(arg: f64) f64;

            // Would like this to be roundss/roundpd/roundsd/roundpd on x86_64+sse4_1

            const f: Vector = input(z);
            const is_negative = bitCastLane(SignedInt, f) < splat(SignedInt, 0);

            const result_is_zero = (splat(Scalar, -0.5) <= f) & (f <= splat(Scalar, 0.5));
            const result_when_zero = select(Scalar, is_negative, @splat(-0.0), @splat(0.0));

            const int_away_from_0 = @round(f);
            const int_to_0 = @round(
                select(Scalar, is_negative, f + splat(Scalar, 1.0), f - splat(Scalar, 1.0)),
            );

            const dist_away_from_0: Vector = @abs(int_away_from_0 - f);
            const dist_to_0: Vector = @abs(int_to_0 - f);

            // rare case where both candidates are of equal distance
            const candidate_round_to_even: Vector = select(
                Scalar,
                away_from_0_is_even: {
                    const CandidateInt = std.math.IntFittingRange(
                        -precise_int_limit,
                        precise_int_limit,
                    );

                    break :away_from_0_is_even @rem(
                        @as(
                            @Vector(vector_len, CandidateInt),
                            away_from_0_as_int: {
                                @setRuntimeSafety(false);
                                break :away_from_0_as_int @intFromFloat(int_away_from_0);
                            },
                        ),
                        splat(CandidateInt, 2),
                    ) == splat(CandidateInt, 0);
                },
                int_away_from_0,
                int_to_0,
            );

            // normal case (not NaN or zero), which also handles infinity
            const select_candidate: Vector = select(
                Scalar,
                dist_away_from_0 < dist_to_0,
                int_away_from_0, // candidate towards zero is closer to original
                select(
                    Scalar,
                    dist_to_0 < dist_away_from_0,
                    dist_to_0, // candidate away from zero is closer to original
                    select(
                        Scalar,
                        (splat(Scalar, -precise_int_limit) < f) &
                            (f < splat(Scalar, precise_int_limit)),
                        candidate_round_to_even,
                        // past the integer limit, only integers are representable anyway
                        int_away_from_0,
                    ),
                ),
            );

            const non_nan: Vector = select(
                Scalar,
                result_is_zero,
                result_when_zero,
                select_candidate,
            );

            const rounded: Vector = select(
                Scalar,
                f != f, // Is this a NaN?
                setCanonicalNanBit(f),
                non_nan,
            );

            return if (is_vector) rounded else rounded[0];
        }
    };
}

const std = @import("std");
